/**
 * Created by vansgare on 6/25/20.
 */


Array
(
    [1] => Array
(
    [810000] => Array
(
    [5] => Array
(
    [1] => Array
(
    [id] => 1
    [extern_id] => 1
    [extern_nama] => lift
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 366721000.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-08-01
    [dtime_start] => 2018-08-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 810000
    [rekening_details] => 30
    [serial_no] => 630 kg; 8 prs
    [kode] => 4thFloor
    [depresiasi] => 1
    [folders] => 5
    [label] => LIFT
    [alias] =>
[nama] => lift
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => General
    [parent_id] => 15
)

[31] => Array
(
    [id] => 4
    [extern_id] => 31
    [extern_nama] => laptop HP 14
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 9790000.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => BP
    [kode] => 29.1
    [depresiasi] => 1
    [folders] => 5
    [label] => laptop
    [alias] =>
[nama] => laptop HP 14
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => HP - 14 inch
    [parent_id] => 9
)

[32] => Array
(
    [id] => 2
    [extern_id] => 32
    [extern_nama] => laptop HP 14
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 9790000.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => BP
    [kode] => 29.2
    [depresiasi] => 1
    [folders] => 5
    [label] => laptop
    [alias] =>
[nama] => laptop HP 14
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => HP - 14 inch
    [parent_id] => 9
)

[33] => Array
(
    [id] => 3
    [extern_id] => 33
    [extern_nama] => laptop HP 14
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 9790000.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => BP
    [kode] => 29.3
    [depresiasi] => 1
    [folders] => 5
    [label] => laptop
    [alias] =>
[nama] => laptop HP 14
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => HP - 14 inch
    [parent_id] => 9
)

[34] => Array
(
    [id] => 5
    [extern_id] => 34
    [extern_nama] => laptop HP 14
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 9790000.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => BP
    [kode] => 29.4
    [depresiasi] => 1
    [folders] => 5
    [label] => laptop
    [alias] =>
[nama] => laptop HP 14
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => HP - 14 inch
    [parent_id] => 9
)

[35] => Array
(
    [id] => 6
    [extern_id] => 35
    [extern_nama] => laptop HP Pro
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 10850000.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => 280
    [kode] => G3.1
    [depresiasi] => 1
    [folders] => 5
    [label] => laptop
    [alias] =>
[nama] => laptop HP Pro
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => HP Pro
    [parent_id] => 10
)

[36] => Array
(
    [id] => 7
    [extern_id] => 36
    [extern_nama] => laptop HP Pro
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 10850000.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => 280
    [kode] => G3.2
    [depresiasi] => 1
    [folders] => 5
    [label] => laptop
    [alias] =>
[nama] => laptop HP Pro
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => HP Pro
    [parent_id] => 10
)

[37] => Array
(
    [id] => 8
    [extern_id] => 37
    [extern_nama] => laptop HP Pro
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 10850000.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => 280
    [kode] => G3.3
    [depresiasi] => 1
    [folders] => 5
    [label] => laptop
    [alias] =>
[nama] => laptop HP Pro
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => HP Pro
    [parent_id] => 10
)

)

[1] => Array
(
    [113] => Array
(
    [id] => 11
    [extern_id] => 113
    [extern_nama] => inova
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 301793796.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2019-06-01
    [dtime_start] => 2019-06-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 1
    [rekening_main] => 810000
    [rekening_details] => 34
    [serial_no] => B 2963 BIC
    [kode] => SAN
    [depresiasi] => 1
    [folders] => 1
    [label] => mobil
    [alias] =>
[nama] => inova
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Toyota
    [parent_id] => 6
)

[114] => Array
(
    [id] => 12
    [extern_id] => 114
    [extern_nama] => inova
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 301793796.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2019-06-01
    [dtime_start] => 2019-06-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 1
    [rekening_main] => 810000
    [rekening_details] => 34
    [serial_no] => B 2055 BIC
    [kode] => HCK
    [depresiasi] => 1
    [folders] => 1
    [label] => mobil
    [alias] =>
[nama] => inova
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Toyota
    [parent_id] => 6
)

[115] => Array
(
    [id] => 10
    [extern_id] => 115
    [extern_nama] => HRV
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 288537391.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2019-06-01
    [dtime_start] => 2019-06-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 1
    [rekening_main] => 810000
    [rekening_details] => 34
    [serial_no] => B 2439
    [kode] => NGDMIN
    [depresiasi] => 1
    [folders] => 1
    [label] => mobil
    [alias] =>
[nama] => HRV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Honda
    [parent_id] => 7
)

[116] => Array
(
    [id] => 83
    [extern_id] => 116
    [extern_nama] => DFSK  MPV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 3
    [value_used] => 15889688
    [harga_perolehan] => 254235000.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2020-02-03
    [dtime_start] => 2020-02-03
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 1
    [rekening_main] => 810000
    [rekening_details] => 34
    [serial_no] =>
[kode] =>
[depresiasi] => 1
    [folders] => 1
    [label] => Kendaraan
    [alias] =>
[nama] => DFSK  MPV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] =>
[parent_id] => 24
)

)

[13] => Array
(
    [64] => Array
(
    [id] => 9
    [extern_id] => 64
    [extern_nama] => forklift
    [cabang_id] => 1
    [jenis] => assets
    [used] => 10
    [value_used] => 5208333.33
    [harga_perolehan] => 25000000.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-11-01
    [dtime_start] => 2018-11-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 1
    [rekening_main] => 810000
    [rekening_details] => 34
    [serial_no] =>
[kode] => Ex Onda
    [depresiasi] => 1
    [folders] => 13
    [label] => forklift
    [alias] =>
[nama] => forklift
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Toyota
    [parent_id] => 19
)

[69] => Array
(
    [id] => 34
    [extern_id] => 69
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2765699,66
    [harga_perolehan] => 5310143.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE50MV14.1
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => daikin
    [parent_id] => 20
)

[70] => Array
(
    [id] => 35
    [extern_id] => 70
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2765699,66
    [harga_perolehan] => 5310143.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE50MV14.2
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => daikin
    [parent_id] => 20
)

[71] => Array
(
    [id] => 36
    [extern_id] => 71
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2765699,66
    [harga_perolehan] => 5310143.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE50MV14.3
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => daikin
    [parent_id] => 20
)

[72] => Array
(
    [id] => 37
    [extern_id] => 72
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2765699,66
    [harga_perolehan] => 5310143.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE50MV14.4
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => daikin
    [parent_id] => 20
)

[73] => Array
(
    [id] => 38
    [extern_id] => 73
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2765699,66
    [harga_perolehan] => 5310143.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE50MV14.5
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => daikin
    [parent_id] => 20
)

[74] => Array
(
    [id] => 39
    [extern_id] => 74
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2765699,66
    [harga_perolehan] => 5310143.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE50MV14.6
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => daikin
    [parent_id] => 20
)

[75] => Array
(
    [id] => 40
    [extern_id] => 75
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2765699,66
    [harga_perolehan] => 5310143.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE50MV14.7
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => daikin
    [parent_id] => 20
)

[76] => Array
(
    [id] => 41
    [extern_id] => 76
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2765699,66
    [harga_perolehan] => 5310143.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE50MV14.8
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => daikin
    [parent_id] => 20
)

[77] => Array
(
    [id] => 42
    [extern_id] => 77
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2765699,66
    [harga_perolehan] => 5310143.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE50MV14.9
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => daikin
    [parent_id] => 20
)

[78] => Array
(
    [id] => 43
    [extern_id] => 78
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2765699,66
    [harga_perolehan] => 5310143.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE50MV14.10
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => daikin
    [parent_id] => 20
)

[79] => Array
(
    [id] => 44
    [extern_id] => 79
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2765699,66
    [harga_perolehan] => 5310143.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE50MV14.11
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => daikin
    [parent_id] => 20
)

[111] => Array
(
    [id] => 33
    [extern_id] => 111
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 2999127.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 810000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE15MV14
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Daikin
    [parent_id] => 20
)

)

)

[710000] => Array
(
    [5] => Array
(
    [38] => Array
(
    [id] => 13
    [extern_id] => 38
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 1747913.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L Shaped
    [kode] => 1800 W GZ 50
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[39] => Array
(
    [id] => 14
    [extern_id] => 39
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 1747913.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L Shaped
    [kode] => 1800 W GZ 50
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[40] => Array
(
    [id] => 15
    [extern_id] => 40
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 1747913.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L Shaped
    [kode] => 1800 W GZ 50
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[41] => Array
(
    [id] => 16
    [extern_id] => 41
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 1635867.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-01-03
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L Shaped Leg
    [kode] => 1500 W GZ50.1
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[42] => Array
(
    [id] => 17
    [extern_id] => 42
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 1635867.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L Shaped Leg
    [kode] => 1500 W GZ50.2
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[43] => Array
(
    [id] => 18
    [extern_id] => 43
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 1635867.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L Shaped Leg
    [kode] => 1500 W GZ50.3
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[44] => Array
(
    [id] => 19
    [extern_id] => 44
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 1635867.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L Shaped Leg
    [kode] => 1500 W GZ50.4
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[45] => Array
(
    [id] => 65
    [extern_id] => 45
    [extern_nama] => sales workstation
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2100856,77
    [harga_perolehan] => 4033645.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => -
    [kode] => -
    [depresiasi] => 1
    [folders] => 5
    [label] => sales workstation
    [alias] =>
[nama] => sales workstation
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => -
    [parent_id] => 12
)

[46] => Array
(
    [id] => 66
    [extern_id] => 46
    [extern_nama] => sales workstation
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2100856,77
    [harga_perolehan] => 4033645.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => -
    [kode] => -
    [depresiasi] => 1
    [folders] => 5
    [label] => sales workstation
    [alias] =>
[nama] => sales workstation
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => -
    [parent_id] => 12
)

[47] => Array
(
    [id] => 67
    [extern_id] => 47
    [extern_nama] => sales workstation
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2100856,77
    [harga_perolehan] => 4033645.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => -
    [kode] => -
    [depresiasi] => 1
    [folders] => 5
    [label] => sales workstation
    [alias] =>
[nama] => sales workstation
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => -
    [parent_id] => 12
)

[48] => Array
(
    [id] => 68
    [extern_id] => 48
    [extern_nama] => sales workstation
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2100856,77
    [harga_perolehan] => 4033645.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => -
    [kode] => -
    [depresiasi] => 1
    [folders] => 5
    [label] => sales workstation
    [alias] =>
[nama] => sales workstation
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => -
    [parent_id] => 12
)

[49] => Array
(
    [id] => 72
    [extern_id] => 49
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1085442,71
    [harga_perolehan] => 2084050.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L shaped Leg
    [kode] => 1800 W GZ 38.1
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[50] => Array
(
    [id] => 73
    [extern_id] => 50
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1085442,71
    [harga_perolehan] => 2084050.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L shaped Leg
    [kode] => 1800 W GZ 38.2
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[51] => Array
(
    [id] => 74
    [extern_id] => 51
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1085442,71
    [harga_perolehan] => 2084050.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L shaped Leg
    [kode] => 1800 W GZ 38.3
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[52] => Array
(
    [id] => 75
    [extern_id] => 52
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1085442,71
    [harga_perolehan] => 2084050.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L shaped Leg
    [kode] => 1800 W GZ 38.4
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[53] => Array
(
    [id] => 76
    [extern_id] => 53
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1085442,71
    [harga_perolehan] => 2084050.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L shaped Leg
    [kode] => 1800 W GZ 38.5
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[54] => Array
(
    [id] => 77
    [extern_id] => 54
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1085442,71
    [harga_perolehan] => 2084050.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L shaped Leg
    [kode] => 1800 W GZ 38.6
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[55] => Array
(
    [id] => 78
    [extern_id] => 55
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1027085,52
    [harga_perolehan] => 1972004.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L Shaped Leg
    [kode] => 1500 W GZ 38.1
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[56] => Array
(
    [id] => 79
    [extern_id] => 56
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1027085,52
    [harga_perolehan] => 1972004.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L Shaped Leg
    [kode] => 1500 W GZ 38.2
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[57] => Array
(
    [id] => 80
    [extern_id] => 57
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1027085,52
    [harga_perolehan] => 1972004.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L Shaped Leg
    [kode] => 1500 W GZ 38.3
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[58] => Array
(
    [id] => 81
    [extern_id] => 58
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1027085,52
    [harga_perolehan] => 1972004.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L Shaped Leg
    [kode] => 1500 W GZ 38.4
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[59] => Array
(
    [id] => 82
    [extern_id] => 59
    [extern_nama] => manager and admin shaped leg
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1027085,52
    [harga_perolehan] => 1972004.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => L Shaped Leg
    [kode] => 1500 W GZ 38.5
    [depresiasi] => 1
    [folders] => 5
    [label] => Meja Kerja
    [alias] =>
[nama] => manager and admin shaped leg
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Manager and admin
    [parent_id] => 13
)

[94] => Array
(
    [id] => 53
    [extern_id] => 94
    [extern_nama] => meeting area for agent training table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 467878,29
    [harga_perolehan] => 898326.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 1.1
    [depresiasi] => 1
    [folders] => 5
    [label] => Meeting area for agent training table
    [alias] =>
[nama] => meeting area for agent training table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Private
    [parent_id] => 14
)

[95] => Array
(
    [id] => 54
    [extern_id] => 95
    [extern_nama] => meeting area for agent training table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 467878,29
    [harga_perolehan] => 898326.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 1.2
    [depresiasi] => 1
    [folders] => 5
    [label] => Meeting area for agent training table
    [alias] =>
[nama] => meeting area for agent training table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Private
    [parent_id] => 14
)

[96] => Array
(
    [id] => 55
    [extern_id] => 96
    [extern_nama] => meeting area for agent training table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 467878,29
    [harga_perolehan] => 898326.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 1.3
    [depresiasi] => 1
    [folders] => 5
    [label] => Meeting area for agent training table
    [alias] =>
[nama] => meeting area for agent training table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Private
    [parent_id] => 14
)

[97] => Array
(
    [id] => 56
    [extern_id] => 97
    [extern_nama] => meeting area for agent training table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 467878,29
    [harga_perolehan] => 898326.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 1.4
    [depresiasi] => 1
    [folders] => 5
    [label] => Meeting area for agent training table
    [alias] =>
[nama] => meeting area for agent training table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Private
    [parent_id] => 14
)

[98] => Array
(
    [id] => 57
    [extern_id] => 98
    [extern_nama] => meeting area for agent training table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 467878,29
    [harga_perolehan] => 898326.0000000000
    [economic_life_time] => 96
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 1.5
    [depresiasi] => 1
    [folders] => 5
    [label] => Meeting area for agent training table
    [alias] =>
[nama] => meeting area for agent training table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Private
    [parent_id] => 14
)

[99] => Array
(
    [id] => 58
    [extern_id] => 99
    [extern_nama] => meeting area for agent training table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 467878,29
    [harga_perolehan] => 898326.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 1.6
    [depresiasi] => 1
    [folders] => 5
    [label] => Meeting area for agent training table
    [alias] =>
[nama] => meeting area for agent training table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Private
    [parent_id] => 14
)

[100] => Array
(
    [id] => 59
    [extern_id] => 100
    [extern_nama] => meeting area for agent training table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 467878,29
    [harga_perolehan] => 898326.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 1.7
    [depresiasi] => 1
    [folders] => 5
    [label] => Meeting area for agent training table
    [alias] =>
[nama] => meeting area for agent training table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Private
    [parent_id] => 14
)

[101] => Array
(
    [id] => 60
    [extern_id] => 101
    [extern_nama] => meeting area for agent training table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 467878,29
    [harga_perolehan] => 898326.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 1.8
    [depresiasi] => 1
    [folders] => 5
    [label] => Meeting area for agent training table
    [alias] =>
[nama] => meeting area for agent training table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Private
    [parent_id] => 14
)

[102] => Array
(
    [id] => 61
    [extern_id] => 102
    [extern_nama] => meeting area for agent training table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 467878,29
    [harga_perolehan] => 898326.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 1.9
    [depresiasi] => 1
    [folders] => 5
    [label] => Meeting area for agent training table
    [alias] =>
[nama] => meeting area for agent training table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Private
    [parent_id] => 14
)

[103] => Array
(
    [id] => 62
    [extern_id] => 103
    [extern_nama] => meeting area for agent training table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 467878,29
    [harga_perolehan] => 898326.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 1.1
    [depresiasi] => 1
    [folders] => 5
    [label] => Meeting area for agent training table
    [alias] =>
[nama] => meeting area for agent training table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Private
    [parent_id] => 14
)

[104] => Array
(
    [id] => 63
    [extern_id] => 104
    [extern_nama] => meeting area for agent training table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 467878,29
    [harga_perolehan] => 898326.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 1.11
    [depresiasi] => 1
    [folders] => 5
    [label] => Meeting area for agent training table
    [alias] =>
[nama] => meeting area for agent training table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Private
    [parent_id] => 14
)

[105] => Array
(
    [id] => 64
    [extern_id] => 105
    [extern_nama] => meeting area for agent training table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 467878,29
    [harga_perolehan] => 898326.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 1.12
    [depresiasi] => 1
    [folders] => 5
    [label] => Meeting area for agent training table
    [alias] =>
[nama] => meeting area for agent training table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Private
    [parent_id] => 14
)

[107] => Array
(
    [id] => 69
    [extern_id] => 107
    [extern_nama] => meeting table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1400571,09
    [harga_perolehan] => 2689097.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] =>
[depresiasi] => 1
    [folders] => 5
    [label] => meeting table
    [alias] =>
[nama] => meeting table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] =>
[parent_id] => 11
)

[108] => Array
(
    [id] => 70
    [extern_id] => 108
    [extern_nama] => meeting table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1400571,09
    [harga_perolehan] => 2689097.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] =>
[depresiasi] => 1
    [folders] => 5
    [label] => meeting table
    [alias] =>
[nama] => meeting table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] =>
[parent_id] => 11
)

[110] => Array
(
    [id] => 71
    [extern_id] => 110
    [extern_nama] => meeting table
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1867430.73
    [harga_perolehan] => 3585467.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 5
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => -
    [kode] => -
    [depresiasi] => 1
    [folders] => 5
    [label] => meeteing table
    [alias] =>
[nama] => meeting table
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => -
    [parent_id] => 11
)

)

[1] => Array
(
    [117] => Array
(
    [id] => 84
    [extern_id] => 117
    [extern_nama] => DPSK Pick UP
    [cabang_id] => 1
    [jenis] => assets
    [used] => 3
    [value_used] => 5876947
    [harga_perolehan] => 94031147.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2020-02-03
    [dtime_start] => 2020-02-03
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 1
    [rekening_main] => 710000
    [rekening_details] => 34
    [serial_no] =>
[kode] =>
[depresiasi] => 1
    [folders] => 1
    [label] => Kendaraan
    [alias] =>
[nama] => DPSK Pick UP
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] =>
[parent_id] => 25
)

)

[13] => Array
(
    [66] => Array
(
    [id] => 45
    [extern_id] => 66
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2094319.62
    [harga_perolehan] => 4021094.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE35MV14.1
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Daikin
    [parent_id] => 20
)

[67] => Array
(
    [id] => 46
    [extern_id] => 67
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2094319,62
    [harga_perolehan] => 4021094.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE35MV14.2
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Daikin
    [parent_id] => 20
)

[68] => Array
(
    [id] => 47
    [extern_id] => 68
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 2094319,62
    [harga_perolehan] => 4021094.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE35MV14.3
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Daikin
    [parent_id] => 20
)

[80] => Array
(
    [id] => 32
    [extern_id] => 80
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1687144
    [harga_perolehan] => 3239317.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE25MV14.1
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Daikin
    [parent_id] => 20
)

[81] => Array
(
    [id] => 31
    [extern_id] => 81
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1687144,27
    [harga_perolehan] => 3239317.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE25MV14.2
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Daikin
    [parent_id] => 20
)

[82] => Array
(
    [id] => 30
    [extern_id] => 82
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1687144,27
    [harga_perolehan] => 3239317.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE25MV14.3
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Daikin
    [parent_id] => 20
)

[83] => Array
(
    [id] => 29
    [extern_id] => 83
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1687144.27
    [harga_perolehan] => 3239317.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 28
    [serial_no] => STNE25MV
    [kode] => RNE25MV14.4
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Daikin
    [parent_id] => 20
)

[84] => Array
(
    [id] => 28
    [extern_id] => 84
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1687144,27
    [harga_perolehan] => 3239317.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE25MV14.5
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Daikin
    [parent_id] => 20
)

[85] => Array
(
    [id] => 27
    [extern_id] => 85
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1687144,27
    [harga_perolehan] => 3239317.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE25MV14.6
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Daikin
    [parent_id] => 20
)

[86] => Array
(
    [id] => 26
    [extern_id] => 86
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1687144,27
    [harga_perolehan] => 3239317.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE25MV14.7
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Daikin
    [parent_id] => 20
)

[87] => Array
(
    [id] => 25
    [extern_id] => 87
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1687144,27
    [harga_perolehan] => 3239317.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE25MV14.8
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Daikin
    [parent_id] => 20
)

[88] => Array
(
    [id] => 24
    [extern_id] => 88
    [extern_nama] => daikin STNE25MV
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 1687144,27
    [harga_perolehan] => 3239317.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] => STNE25MV
    [kode] => RNE25MV14.9
    [depresiasi] => 1
    [folders] => 13
    [label] => Peralatan - AC
    [alias] =>
[nama] => daikin STNE25MV
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Daikin
    [parent_id] => 20
)

[89] => Array
(
    [id] => 48
    [extern_id] => 89
    [extern_nama] => toto U57
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 854391,56
    [harga_perolehan] => 1640432.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 57.1
    [depresiasi] => 1
    [folders] => 13
    [label] => Sanitary - Set
    [alias] =>
[nama] => toto U57
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => toto U57
    [parent_id] => 21
)

[90] => Array
(
    [id] => 49
    [extern_id] => 90
    [extern_nama] => toto U57
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 854391,56
    [harga_perolehan] => 1640432.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 57.2
    [depresiasi] => 1
    [folders] => 13
    [label] => Sanitary - Set
    [alias] =>
[nama] => toto U57
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => toto U57
    [parent_id] => 21
)

[91] => Array
(
    [id] => 50
    [extern_id] => 91
    [extern_nama] => toto U57
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 854391,56
    [harga_perolehan] => 1640432.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 57.3
    [depresiasi] => 1
    [folders] => 13
    [label] => Sanitary - Set
    [alias] =>
[nama] => toto U57
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => toto U57
    [parent_id] => 21
)

[92] => Array
(
    [id] => 51
    [extern_id] => 92
    [extern_nama] => toto U57
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 854391,56
    [harga_perolehan] => 1640432.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 57.4
    [depresiasi] => 1
    [folders] => 13
    [label] => Sanitary - Set
    [alias] =>
[nama] => toto U57
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => toto U57
    [parent_id] => 21
)

[93] => Array
(
    [id] => 52
    [extern_id] => 93
    [extern_nama] => toto U57
    [cabang_id] => 1
    [jenis] => assets
    [used] => 25
    [value_used] => 854391,56
    [harga_perolehan] => 1640432.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-03-01
    [dtime_start] => 2018-03-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 710000
    [rekening_details] => 33
    [serial_no] =>
[kode] => 57.5
    [depresiasi] => 1
    [folders] => 13
    [label] => Sanitary - Set
    [alias] =>
[nama] => toto U57
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => toto U57
    [parent_id] => 21
)

)

)

)

[25] => Array
(
    [4] => Array
(
    [9] => Array
(
    [60] => Array
(
    [id] => 21
    [extern_id] => 60
    [extern_nama] => mixer
    [cabang_id] => 25
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 130000000.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-04-01
    [dtime_start] => 2018-04-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 9
    [rekening_main] => 4
    [rekening_details] =>
[serial_no] =>
[kode] => 1
    [depresiasi] => 1
    [folders] => 9
    [label] => mixer
    [alias] =>
[nama] => mixer
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => SAMA
    [parent_id] => 16
)

[61] => Array
(
    [id] => 22
    [extern_id] => 61
    [extern_nama] => sprayer
    [cabang_id] => 25
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 49325000.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-05-01
    [dtime_start] => 2018-05-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 9
    [rekening_main] => 4
    [rekening_details] =>
[serial_no] => -
    [kode] => W71N
    [depresiasi] => 1
    [folders] => 9
    [label] => sprayer
    [alias] =>
[nama] => sprayer
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => ITALCO
    [parent_id] => 17
)

[63] => Array
(
    [id] => 23
    [extern_id] => 63
    [extern_nama] => moulding
    [cabang_id] => 25
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 25881000.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-10-01
    [dtime_start] => 2018-10-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 9
    [rekening_main] => 4
    [rekening_details] =>
[serial_no] => material550C
    [kode] => 1
    [depresiasi] => 1
    [folders] => 9
    [label] => moulding
    [alias] =>
[nama] => moulding
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => IDDA
    [parent_id] => 18
)

)

[13] => Array
(
    [62] => Array
(
    [id] => 20
    [extern_id] => 62
    [extern_nama] => forklift
    [cabang_id] => 25
    [jenis] => assets
    [used] =>
[value_used] =>
[harga_perolehan] => 139545455.0000000000
    [economic_life_time] => 48
    [residual_value] => 1
    [status] => 1
    [trash] => 0
    [dtime_perolehan] => 2018-04-01
    [dtime_start] => 2018-04-01
    [repeat] => 21
    [gudang_id] =>
[economic_life_label] =>
[note] =>
[asset_account] => 13
    [rekening_main] => 4
    [rekening_details] =>
[serial_no] => 60-8FD25
    [kode] => MT
    [depresiasi] => 1
    [folders] => 13
    [label] => forklift
    [alias] =>
[nama] => forklift
    [keterangan] =>
[deskripsi] =>
[satuan] => n/a
    [no_part] =>
[merk] => Toyota 2.5T
    [parent_id] => 19
)

)

)

)

)