<?php

class MataUang
{
    function _construct()
    {
        $db = new DB_Class();
    }

    public function _arr_valas()
    {
        $_arr_valas = array(
            'AED'=>array( 'code'=>'AED',        'sysLoc'=>'F',     'symbol'=>'د.إ',      'f1'=>'dirham',    'f2'=>'Fils'        ),
            'AFN'=>array( 'code'=>'AFN',        'sysLoc'=>'F',     'symbol'=>'؋',        'f1'=>'afghani',   'f2'=>'Pul'         ),
            'ALL'=>array( 'code'=>'ALL',        'sysLoc'=>'F',     'symbol'=>'L',        'f1'=>'lek',       'f2'=>'Qindarkë'    ),
            'AMD'=>array( 'code'=>'AMD',        'sysLoc'=>'F',     'symbol'=>'֏',        'f1'=>'dram',      'f2'=>'Luma'        ),
            'ANG'=>array( 'code'=>'ANG',        'sysLoc'=>'F',     'symbol'=>'ƒ',        'f1'=>'guilder',   'f2'=>'Cent'        ),
            'AOA'=>array( 'code'=>'AOA',        'sysLoc'=>'F',     'symbol'=>'Kz',       'f1'=>'kwanza',    'f2'=>'Cêntimo'     ),
            'ARS'=>array( 'code'=>'ARS',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'peso',      'f2'=>'Centavo'     ),
            'AUD'=>array( 'code'=>'AUD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'AWG'=>array( 'code'=>'AWG',        'sysLoc'=>'F',     'symbol'=>'ƒ',        'f1'=>'florin',    'f2'=>'Cent'        ),
            'AZN'=>array( 'code'=>'AZN',        'sysLoc'=>'F',     'symbol'=>'₼',        'f1'=>'manat',     'f2'=>'Qəpik'       ),
            'BAM'=>array( 'code'=>'BAM',        'sysLoc'=>'F',     'symbol'=>'КМ',       'f1'=>'mark',      'f2'=>'Fening'      ),
            'BBD'=>array( 'code'=>'BBD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'BDT'=>array( 'code'=>'BDT',        'sysLoc'=>'F',     'symbol'=>'৳',        'f1'=>'taka',      'f2'=>'Poisha'      ),
            'BGN'=>array( 'code'=>'BGN',        'sysLoc'=>'F',     'symbol'=>'лв',       'f1'=>'lev',       'f2'=>'Stotinka'    ),
            'BHD'=>array( 'code'=>'BHD',        'sysLoc'=>'F',     'symbol'=>'.د.ب',     'f1'=>'dinar',     'f2'=>'Fils'        ),
            'BIF'=>array( 'code'=>'BIF',        'sysLoc'=>'F',     'symbol'=>'Fr',       'f1'=>'franc',     'f2'=>'Centime'     ),
            'BMD'=>array( 'code'=>'BMD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'BND'=>array( 'code'=>'BND',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Sen'         ),
            'BOB'=>array( 'code'=>'BOB',        'sysLoc'=>'F',     'symbol'=>'Bs.',      'f1'=>'boliviano', 'f2'=>'Centavo'     ),
            'BRL'=>array( 'code'=>'BRL',        'sysLoc'=>'F',     'symbol'=>'R$',       'f1'=>'real',      'f2'=>'Centavo'     ),
            'BSD'=>array( 'code'=>'BSD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'BTN'=>array( 'code'=>'BTN',        'sysLoc'=>'F',     'symbol'=>'Nu.',      'f1'=>'ngultrum',  'f2'=>'Chetrum'     ),
            'BWP'=>array( 'code'=>'BWP',        'sysLoc'=>'F',     'symbol'=>'P',        'f1'=>'pula',      'f2'=>'Thebe'       ),
            'BYN'=>array( 'code'=>'BYN',        'sysLoc'=>'F',     'symbol'=>'Br',       'f1'=>'ruble',     'f2'=>'Kapyeyka'    ),
            'BZD'=>array( 'code'=>'BZD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'CAD'=>array( 'code'=>'CAD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'CDF'=>array( 'code'=>'CDF',        'sysLoc'=>'F',     'symbol'=>'Fr',       'f1'=>'franc',     'f2'=>'Centime'     ),
            'CHF'=>array( 'code'=>'CHF',        'sysLoc'=>'F',     'symbol'=>'CHF',      'f1'=>'franc',     'f2'=>'Rappen'      ),
            'CLP'=>array( 'code'=>'CLP',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'peso',      'f2'=>'Centavo'     ),
            'CNY'=>array( 'code'=>'CNY',        'sysLoc'=>'F',     'symbol'=>'¥',        'f1'=>'yuan',      'f2'=>'Fen'         ),
            'RMB'=>array( 'code'=>'RMB',        'sysLoc'=>'F',     'symbol'=>'¥',        'f1'=>'yuan',      'f2'=>'Fen'         ),
            'COP'=>array( 'code'=>'COP',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'peso',      'f2'=>'Centavo'     ),
            'CRC'=>array( 'code'=>'CRC',        'sysLoc'=>'F',     'symbol'=>'₡',        'f1'=>'colón',     'f2'=>'Céntimo'     ),
            'CUC'=>array( 'code'=>'CUC',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'peso',      'f2'=>'Centavo'     ),
            'CUP'=>array( 'code'=>'CUP',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'peso',      'f2'=>'Centavo'     ),
            'CVE'=>array( 'code'=>'CVE',        'sysLoc'=>'F',     'symbol'=>'Esc',      'f1'=>'escudo',    'f2'=>'Centavo'     ),
            'CZK'=>array( 'code'=>'CZK',        'sysLoc'=>'F',     'symbol'=>'Kč',       'f1'=>'koruna',    'f2'=>'Haléř'       ),
            'DJF'=>array( 'code'=>'DJF',        'sysLoc'=>'F',     'symbol'=>'Fr',       'f1'=>'franc',     'f2'=>'Centime'     ),
            'DKK'=>array( 'code'=>'DKK',        'sysLoc'=>'F',     'symbol'=>'kr',       'f1'=>'krone',     'f2'=>'Øre'         ),
            'DOP'=>array( 'code'=>'DOP',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'peso',      'f2'=>'Centavo'     ),
            'DZD'=>array( 'code'=>'DZD',        'sysLoc'=>'F',     'symbol'=>'د.ج',      'f1'=>'dinar',     'f2'=>'Santeem'     ),
            'EGP'=>array( 'code'=>'EGP',        'sysLoc'=>'F',     'symbol'=>'£',        'f1'=>'pound',     'f2'=>'Piastre'     ),
            'ERN'=>array( 'code'=>'ERN',        'sysLoc'=>'F',     'symbol'=>'Nfk',      'f1'=>'nakfa',     'f2'=>'Cent'        ),
            'ETB'=>array( 'code'=>'ETB',        'sysLoc'=>'F',     'symbol'=>'Br',       'f1'=>'birr',      'f2'=>'Santim'      ),
            'EUR'=>array( 'code'=>'EUR',        'sysLoc'=>'F',     'symbol'=>'€',        'f1'=>'Euro',      'f2'=>'Cent'        ),
            'FJD'=>array( 'code'=>'FJD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'FKP'=>array( 'code'=>'FKP',        'sysLoc'=>'F',     'symbol'=>'£',        'f1'=>'pound',     'f2'=>'Penny'       ),
            'GBP'=>array( 'code'=>'GBP',        'sysLoc'=>'F',     'symbol'=>'£',        'f1'=>'pound',     'f2'=>'Penny'       ),
            'GEL'=>array( 'code'=>'GEL',        'sysLoc'=>'F',     'symbol'=>'₾',        'f1'=>'lari',      'f2'=>'Tetri'       ),
            'GGP'=>array( 'code'=>'GGP',        'sysLoc'=>'F',     'symbol'=>'£',        'f1'=>'pound',     'f2'=>'Penny'       ),
            'GHS'=>array( 'code'=>'GHS',        'sysLoc'=>'F',     'symbol'=>'₵',        'f1'=>'cedi',      'f2'=>'Pesewa'      ),
            'GIP'=>array( 'code'=>'GIP',        'sysLoc'=>'F',     'symbol'=>'£',        'f1'=>'pound',     'f2'=>'Penny'       ),
            'GMD'=>array( 'code'=>'GMD',        'sysLoc'=>'F',     'symbol'=>'D',        'f1'=>'dalasi',    'f2'=>'Butut'       ),
            'GNF'=>array( 'code'=>'GNF',        'sysLoc'=>'F',     'symbol'=>'Fr',       'f1'=>'franc',     'f2'=>'Centime'     ),
            'GTQ'=>array( 'code'=>'GTQ',        'sysLoc'=>'F',     'symbol'=>'Q',        'f1'=>'quetzal',   'f2'=>'Centavo'     ),
            'GYD'=>array( 'code'=>'GYD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'HKD'=>array( 'code'=>'HKD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'HNL'=>array( 'code'=>'HNL',        'sysLoc'=>'F',     'symbol'=>'L',        'f1'=>'lempira',   'f2'=>'Centavo'     ),
            'HRK'=>array( 'code'=>'HRK',        'sysLoc'=>'F',     'symbol'=>'kn',       'f1'=>'kuna',      'f2'=>'Lipa'        ),
            'HTG'=>array( 'code'=>'HTG',        'sysLoc'=>'F',     'symbol'=>'G',        'f1'=>'gourde',    'f2'=>'Centime'     ),
            'HUF'=>array( 'code'=>'HUF',        'sysLoc'=>'F',     'symbol'=>'Ft',       'f1'=>'forint',    'f2'=>'Fillér'      ),
            'IDR'=>array( 'code'=>'IDR',        'sysLoc'=>'F',     'symbol'=>'Rp',       'f1'=>'rupiah',    'f2'=>'Sen'         ),
            'ILS'=>array( 'code'=>'ILS',        'sysLoc'=>'F',     'symbol'=>'₪',        'f1'=>'shekel',    'f2'=>'Agora'       ),
            'IMP'=>array( 'code'=>'IMP',        'sysLoc'=>'F',     'symbol'=>'£',        'f1'=>'pound',     'f2'=>'Penny'       ),
            'INR'=>array( 'code'=>'INR',        'sysLoc'=>'F',     'symbol'=>'₹',        'f1'=>'rupee',     'f2'=>'Paisa'       ),
            'IQD'=>array( 'code'=>'IQD',        'sysLoc'=>'F',     'symbol'=>'ع.د',      'f1'=>'dinar',     'f2'=>'Fils'        ),
            'IRR'=>array( 'code'=>'IRR',        'sysLoc'=>'F',     'symbol'=>'﷼',        'f1'=>'rial',      'f2'=>'Dinar'       ),
            'ISK'=>array( 'code'=>'ISK',        'sysLoc'=>'F',     'symbol'=>'kr',       'f1'=>'króna',     'f2'=>'Eyrir'       ),
            'JEP'=>array( 'code'=>'JEP',        'sysLoc'=>'F',     'symbol'=>'£',        'f1'=>'pound',     'f2'=>'Penny'       ),
            'JMD'=>array( 'code'=>'JMD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'JOD'=>array( 'code'=>'JOD',        'sysLoc'=>'F',     'symbol'=>'د.ا',      'f1'=>'dinar',     'f2'=>'Piastre'     ),
            'JPY'=>array( 'code'=>'JPY',        'sysLoc'=>'F',     'symbol'=>'¥',        'f1'=>'yen',       'f2'=>'Sen'         ),
            'KES'=>array( 'code'=>'KES',        'sysLoc'=>'F',     'symbol'=>'Sh',       'f1'=>'shilling',  'f2'=>'Cent'        ),
            'KGS'=>array( 'code'=>'KGS',        'sysLoc'=>'F',     'symbol'=>'с',        'f1'=>'som',       'f2'=>'Tyiyn'       ),
            'KHR'=>array( 'code'=>'KHR',        'sysLoc'=>'F',     'symbol'=>'៛',        'f1'=>'riel',      'f2'=>'Sen'         ),
            'KID'=>array( 'code'=>'KID',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'KMF'=>array( 'code'=>'KMF',        'sysLoc'=>'F',     'symbol'=>'Fr',       'f1'=>'franc',     'f2'=>'Centime'     ),
            'KPW'=>array( 'code'=>'KPW',        'sysLoc'=>'F',     'symbol'=>'₩',        'f1'=>'won',       'f2'=>'Chon'        ),
            'KRW'=>array( 'code'=>'KRW',        'sysLoc'=>'F',     'symbol'=>'₩',        'f1'=>'won',       'f2'=>'Jeon'        ),
            'KWD'=>array( 'code'=>'KWD',        'sysLoc'=>'F',     'symbol'=>'د.ك',      'f1'=>'dinar',     'f2'=>'Fils'        ),
            'KYD'=>array( 'code'=>'KYD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'KZT'=>array( 'code'=>'KZT',        'sysLoc'=>'F',     'symbol'=>'₸',        'f1'=>'tenge',     'f2'=>'Tïın'        ),
            'LAK'=>array( 'code'=>'LAK',        'sysLoc'=>'F',     'symbol'=>'₭',        'f1'=>'kip',       'f2'=>'Att'         ),
            'LBP'=>array( 'code'=>'LBP',        'sysLoc'=>'F',     'symbol'=>'ل.ل',      'f1'=>'pound',     'f2'=>'Piastre'     ),
            'LKR'=>array( 'code'=>'LKR',        'sysLoc'=>'F',     'symbol'=>'Rs',       'f1'=>'rupee',     'f2'=>'Cent'        ),
            'LRD'=>array( 'code'=>'LRD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'LSL'=>array( 'code'=>'LSL',        'sysLoc'=>'F',     'symbol'=>'L',        'f1'=>'loti',      'f2'=>'Sente'       ),
            'LYD'=>array( 'code'=>'LYD',        'sysLoc'=>'F',     'symbol'=>'ل.د',      'f1'=>'dinar',     'f2'=>'Dirham'      ),
            'MAD'=>array( 'code'=>'MAD',        'sysLoc'=>'F',     'symbol'=>'د.م.',     'f1'=>'dirham',    'f2'=>'Centime'     ),
            'MDL'=>array( 'code'=>'MDL',        'sysLoc'=>'F',     'symbol'=>'L',        'f1'=>'leu',       'f2'=>'Ban'         ),
            'MGA'=>array( 'code'=>'MGA',        'sysLoc'=>'F',     'symbol'=>'Ar',       'f1'=>'ariary',    'f2'=>'Iraimbilanja'),
            'MKD'=>array( 'code'=>'MKD',        'sysLoc'=>'F',     'symbol'=>'ден',      'f1'=>'denar',     'f2'=>'Deni'        ),
            'MMK'=>array( 'code'=>'MMK',        'sysLoc'=>'F',     'symbol'=>'Ks',       'f1'=>'kyat',      'f2'=>'Pya'         ),
            'MNT'=>array( 'code'=>'MNT',        'sysLoc'=>'F',     'symbol'=>'₮',        'f1'=>'tögrög',    'f2'=>'Möngö'       ),
            'MOP'=>array( 'code'=>'MOP',        'sysLoc'=>'F',     'symbol'=>'P',        'f1'=>'pataca',    'f2'=>'Avo'         ),
            'MRU'=>array( 'code'=>'MRU',        'sysLoc'=>'F',     'symbol'=>'UM',       'f1'=>'ouguiya',   'f2'=>'Khoums'      ),
            'MUR'=>array( 'code'=>'MUR',        'sysLoc'=>'F',     'symbol'=>'₨',        'f1'=>'rupee',     'f2'=>'Cent'        ),
            'MVR'=>array( 'code'=>'MVR',        'sysLoc'=>'F',     'symbol'=>'.ރ',       'f1'=>'rufiyaa',   'f2'=>'Laari'       ),
            'MWK'=>array( 'code'=>'MWK',        'sysLoc'=>'F',     'symbol'=>'MK',       'f1'=>'kwacha',    'f2'=>'Tambala'     ),
            'MXN'=>array( 'code'=>'MXN',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'peso',      'f2'=>'Centavo'     ),
            'MYR'=>array( 'code'=>'MYR',        'sysLoc'=>'F',     'symbol'=>'RM',       'f1'=>'ringgit',   'f2'=>'Sen'         ),
            'MZN'=>array( 'code'=>'MZN',        'sysLoc'=>'F',     'symbol'=>'MT',       'f1'=>'metical',   'f2'=>'Centavo'     ),
            'NAD'=>array( 'code'=>'NAD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'NGN'=>array( 'code'=>'NGN',        'sysLoc'=>'F',     'symbol'=>'₦',        'f1'=>'naira',     'f2'=>'Kobo'        ),
            'NIO'=>array( 'code'=>'NIO',        'sysLoc'=>'F',     'symbol'=>'C$',       'f1'=>'córdoba',   'f2'=>'Centavo'     ),
            'NOK'=>array( 'code'=>'NOK',        'sysLoc'=>'F',     'symbol'=>'kr',       'f1'=>'krone',     'f2'=>'Øre'         ),
            'NPR'=>array( 'code'=>'NPR',        'sysLoc'=>'F',     'symbol'=>'₨',        'f1'=>'rupee',     'f2'=>'Paisa'       ),
            'NZD'=>array( 'code'=>'NZD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'OMR'=>array( 'code'=>'OMR',        'sysLoc'=>'F',     'symbol'=>'ر.ع.',     'f1'=>'rial',      'f2'=>'Baisa'       ),
            'PAB'=>array( 'code'=>'PAB',        'sysLoc'=>'F',     'symbol'=>'B/.',      'f1'=>'balboa',    'f2'=>'Centésimo'   ),
            'PEN'=>array( 'code'=>'PEN',        'sysLoc'=>'F',     'symbol'=>'S/.',      'f1'=>'sol',       'f2'=>'Céntimo'     ),
            'PGK'=>array( 'code'=>'PGK',        'sysLoc'=>'F',     'symbol'=>'K',        'f1'=>'kina',      'f2'=>'Toea'        ),
            'PHP'=>array( 'code'=>'PHP',        'sysLoc'=>'F',     'symbol'=>'₱',        'f1'=>'peso',      'f2'=>'Sentimo'     ),
            'PKR'=>array( 'code'=>'PKR',        'sysLoc'=>'F',     'symbol'=>'₨',        'f1'=>'rupee',     'f2'=>'Paisa'       ),
            'PLN'=>array( 'code'=>'PLN',        'sysLoc'=>'F',     'symbol'=>'zł',       'f1'=>'złoty',     'f2'=>'Grosz'       ),
            'PRB'=>array( 'code'=>'PRB',        'sysLoc'=>'F',     'symbol'=>'р.',       'f1'=>'ruble',     'f2'=>'Kopek'       ),
            'PYG'=>array( 'code'=>'PYG',        'sysLoc'=>'F',     'symbol'=>'₲',        'f1'=>'guaraní',    'f2'=>'Céntimo'    ),
            'QAR'=>array( 'code'=>'QAR',        'sysLoc'=>'F',     'symbol'=>'ر.ق',      'f1'=>'riyal',     'f2'=>'Dirham'      ),
            'RON'=>array( 'code'=>'RON',        'sysLoc'=>'F',     'symbol'=>'lei',      'f1'=>'leu',       'f2'=>'Ban'         ),
            'RSD'=>array( 'code'=>'RSD',        'sysLoc'=>'F',     'symbol'=>'дин.',     'f1'=>'dinar',     'f2'=>'Para'        ),
            'RUB'=>array( 'code'=>'RUB',        'sysLoc'=>'F',     'symbol'=>'₽',        'f1'=>'ruble',     'f2'=>'Kopek'       ),
            'RWF'=>array( 'code'=>'RWF',        'sysLoc'=>'F',     'symbol'=>'Fr',       'f1'=>'franc',     'f2'=>'Centime'     ),
            'SAR'=>array( 'code'=>'SAR',        'sysLoc'=>'F',     'symbol'=>'ر.س',      'f1'=>'riyal',     'f2'=>'Halala'      ),
            'SBD'=>array( 'code'=>'SBD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'SCR'=>array( 'code'=>'SCR',        'sysLoc'=>'F',     'symbol'=>'₨',       'f1'=>'rupee',     'f2'=>'Cent'         ),
            'SDG'=>array( 'code'=>'SDG',        'sysLoc'=>'F',     'symbol'=>'ج.س.',     'f1'=>'pound',     'f2'=>'Piastre'     ),
            'SEK'=>array( 'code'=>'SEK',        'sysLoc'=>'F',     'symbol'=>'kr',       'f1'=>'krona',     'f2'=>'Öre'         ),
            'SGD'=>array( 'code'=>'SGD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'SHP'=>array( 'code'=>'SHP',        'sysLoc'=>'F',     'symbol'=>'£',        'f1'=>'pound',     'f2'=>'Penny'       ),
            'SLL'=>array( 'code'=>'SLL',        'sysLoc'=>'F',     'symbol'=>'Le',       'f1'=>'leone',     'f2'=>'Cent'        ),
            'SLS'=>array( 'code'=>'SLS',        'sysLoc'=>'F',     'symbol'=>'Sl',       'f1'=>'shilling',  'f2'=>'Cent'        ),
            'SOS'=>array( 'code'=>'SOS',        'sysLoc'=>'F',     'symbol'=>'Sh',       'f1'=>'shilling',  'f2'=>'Cent'        ),
            'SRD'=>array( 'code'=>'SRD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'SSP'=>array( 'code'=>'SSP',        'sysLoc'=>'F',     'symbol'=>'£',        'f1'=>'pound',     'f2'=>'Piastre'     ),
            'STN'=>array( 'code'=>'STN',        'sysLoc'=>'F',     'symbol'=>'Db',       'f1'=>'dobra',     'f2'=>'Cêntimo'     ),
            'SYP'=>array( 'code'=>'SYP',        'sysLoc'=>'F',     'symbol'=>'£',        'f1'=>'pound',     'f2'=>'Piastre'     ),
            'SZL'=>array( 'code'=>'SZL',        'sysLoc'=>'F',     'symbol'=>'L',        'f1'=>'lilangeni', 'f2'=>'Cent'        ),
            'THB'=>array( 'code'=>'THB',        'sysLoc'=>'F',     'symbol'=>'฿',        'f1'=>'baht',      'f2'=>'Satang'      ),
            'TJS'=>array( 'code'=>'TJS',        'sysLoc'=>'F',     'symbol'=>'ЅМ',       'f1'=>'somoni',    'f2'=>'Diram'       ),
            'TMT'=>array( 'code'=>'TMT',        'sysLoc'=>'F',     'symbol'=>'m',        'f1'=>'manat',     'f2'=>'Tennesi'     ),
            'TND'=>array( 'code'=>'TND',        'sysLoc'=>'F',     'symbol'=>'د.ت',      'f1'=>'dinar',     'f2'=>'Millime'     ),
            'TOP'=>array( 'code'=>'TOP',        'sysLoc'=>'F',     'symbol'=>'T$',       'f1'=>'paʻanga',   'f2'=>'Seniti'      ),
            'TRY'=>array( 'code'=>'TRY',        'sysLoc'=>'F',     'symbol'=>'₺',        'f1'=>'lira',      'f2'=>'Kuruş'       ),
            'TTD'=>array( 'code'=>'TTD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'TVD'=>array( 'code'=>'TVD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'TWD'=>array( 'code'=>'TWD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'TZS'=>array( 'code'=>'TZS',        'sysLoc'=>'F',     'symbol'=>'Sh',       'f1'=>'shilling',  'f2'=>'Cent'        ),
            'UAH'=>array( 'code'=>'UAH',        'sysLoc'=>'F',     'symbol'=>'₴',        'f1'=>'hryvnia',   'f2'=>'Kopiyka'     ),
            'UGX'=>array( 'code'=>'UGX',        'sysLoc'=>'F',     'symbol'=>'Sh',       'f1'=>'shilling',  'f2'=>'Cent'        ),
            'USD'=>array( 'code'=>'USD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'UYU'=>array( 'code'=>'UYU',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'peso',      'f2'=>'Centésimo'   ),
            'UZS'=>array( 'code'=>'UZS',        'sysLoc'=>'F',     'symbol'=>'сўм',      'f1'=>'soʻm',      'f2'=>'Tiyin'       ),
            'VES'=>array( 'code'=>'VES',        'sysLoc'=>'F',     'symbol'=>'Bs.',      'f1'=>'soberano',  'f2'=>'Céntimo'     ),
            'VND'=>array( 'code'=>'VND',        'sysLoc'=>'F',     'symbol'=>'₫',        'f1'=>'đồng',      'f2'=>'Hào'         ),
            'VUV'=>array( 'code'=>'VUV',        'sysLoc'=>'F',     'symbol'=>'Vt',       'f1'=>'vatu',      'f2'=>''            ),
            'WST'=>array( 'code'=>'WST',        'sysLoc'=>'F',     'symbol'=>'T',        'f1'=>'tālā',      'f2'=>'Sene'        ),
            'XAF'=>array( 'code'=>'XAF',        'sysLoc'=>'F',     'symbol'=>'Fr',       'f1'=>'franc',     'f2'=>'Centime'     ),
            'XCD'=>array( 'code'=>'XCD',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'dollar',    'f2'=>'Cent'        ),
            'XOF'=>array( 'code'=>'XOF',        'sysLoc'=>'F',     'symbol'=>'Fr',       'f1'=>'franc',     'f2'=>'Centime'     ),
            'XPF'=>array( 'code'=>'XPF',        'sysLoc'=>'F',     'symbol'=>'₣',        'f1'=>'franc',     'f2'=>'Centime'     ),
            'YER'=>array( 'code'=>'YER',        'sysLoc'=>'F',     'symbol'=>'﷼',        'f1'=>'rial',      'f2'=>'Fils'        ),
            'ZAR'=>array( 'code'=>'ZAR',        'sysLoc'=>'F',     'symbol'=>'R',        'f1'=>'rand',      'f2'=>'Cent'        ),
            'ZMW'=>array( 'code'=>'ZMW',        'sysLoc'=>'F',     'symbol'=>'ZK',       'f1'=>'kwacha',    'f2'=>'Ngwee'       ),
            'ZWB'=>array( 'code'=>'ZWB',        'sysLoc'=>'F',     'symbol'=>'$',        'f1'=>'bonds',     'f2'=>'Cent'        )
        );

        return $_arr_valas;
    }


    public function getMataUang($code='')
    {
        if($code==''){ die('you not yet define ISO code'); }
        $arrValas = $this->_arr_valas();
        return $arrValas[$code];
    }


}




?>