<?php
defined('BASEPATH') OR exit('No direct script access allowed');


$active_group = 'default';
$query_builder = true;

$db['default'] = array(
    'dsn' => '',
    //---------------------------------------------
     'hostname'     => '192.168.5.14',
     'database'     => 'everest_23des',
//    'hostname'     => '192.168.11.100',
//    'database'     => 'run_everest_modul',

    //---------------------------------------------
    'username' => 'admin',
    'password' => 'mayanet619955',
    'dbdriver' => 'mysqli',
    'dbprefix' => '',
    'pconnect' => false,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => false,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => false,
    'compress' => false,
    'stricton' => false,
    'failover' => array(),
    'save_queries' => true,
);
$db['postman'] = array(
    'dsn' => '',
    // 'hostname'     => 'localhost',
    //    'hostname' => '192.168.11.101',
    'hostname' => '192.168.11.100',
    'username' => 'admin',
    'password' => 'mayanet619955',
    'database' => 'postman',
    // 'database'     => 'legit_vitocafe',
    'dbdriver' => 'mysqli',
    'dbprefix' => '',
    'pconnect' => false,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => false,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => false,
    'compress' => false,
    'stricton' => false,
    'failover' => array(),
    'save_queries' => true,
);
//$db['report'] = array(
//    'dsn' => '',
//    // 'hostname' => '192.168.11.101',
//    'hostname' => '192.168.5.14',
//    'database' => 'run_ev_report',
//    'username' => 'admin',
//    'password' => 'mayanet619955',
//    'dbdriver' => 'mysqli',
//    'dbprefix' => '',
//    'pconnect' => false,
//    'db_debug' => (ENVIRONMENT !== 'production'),
//    'cache_on' => false,
//    'cachedir' => '',
//    'char_set' => 'utf8',
//    'dbcollat' => 'utf8_general_ci',
//    'swap_pre' => '',
//    'encrypt' => false,
//    'compress' => false,
//    'stricton' => false,
//    'failover' => array(),
//    'save_queries' => true,
//);
//$db['route'] = array(
//    'dsn' => '',
//    'hostname' => '192.168.11.150',
//    //    'hostname'     => 'localhost',
//    'database' => 'route',
//    'username' => 'admin',
//    'password' => 'mayanet619955',
//    'dbdriver' => 'mysqli',
//    'dbprefix' => '',
//    'pconnect' => false,
//    'db_debug' => (ENVIRONMENT !== 'production'),
//    'cache_on' => false,
//    'cachedir' => '',
//    'char_set' => 'utf8',
//    'dbcollat' => 'utf8_general_ci',
//    'swap_pre' => '',
//    'encrypt' => false,
//    'compress' => false,
//    'stricton' => false,
//    'failover' => array(),
//    'save_queries' => true,
//);
// $db['testing'] = array(
//    'dsn' => '',
//    'hostname'     => '192.168.5.14',
//    'database' => 'run_ev_report',
//    'username' => 'admin',
//    'password' => 'mayanet619955',
//    'dbdriver' => 'mysqli',
//    'dbprefix' => '',
//    'pconnect' => false,
//    'db_debug' => (ENVIRONMENT !== 'production'),
//    'cache_on' => false,
//    'cachedir' => '',
//    'char_set' => 'utf8',
//    'dbcollat' => 'utf8_general_ci',
//    'swap_pre' => '',
//    'encrypt' => false,
//    'compress' => false,
//    'stricton' => false,
//    'failover' => array(),
//    'save_queries' => true,
// );